apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-appconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  ENABLE_DAPR: "true"
  DAPR_PUBSUB_NAME: "kafka-pubsub"
  TASK_EVENTS_TOPIC: "task-events"
  REMINDERS_TOPIC: "reminders"
  # Add other application-specific configurations here as key-value pairs
  # e.g., API_BASE_URL: "http://my-backend-service"