apiVersion: v1
kind: Secret
metadata:
  name: neon-db-secret
  namespace: todo-app
type: Opaque
stringData:
  connection-string: "postgresql://neondb_owner:npg_y2AxfnYdLmk7@ep-young-union-ahyord23-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
  dapr-connection-string: "postgresql://neondb_owner:npg_y2AxfnYdLmk7@ep-young-union-ahyord23.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require"
