apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-config
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: todo-backend
data:
  ENVIRONMENT: {{ .Values.environment.name | quote }}
  LOG_LEVEL: "INFO"