apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend-config
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: todo-frontend
data:
  NEXT_PUBLIC_API_URL: "http://todo.local/api"
  ENVIRONMENT: {{ .Values.environment.name | quote }}