apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: todo-app
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: ""
  metric:
    enabled: true
  features:
  - name: ServiceInvocation
    enabled: true
