apiVersion: apps/v1
kind: Deployment
metadata:
  name: recurring-task-service
  namespace: todo-app
  labels:
    app: recurring-task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recurring-task-service
  template:
    metadata:
      labels:
        app: recurring-task-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "recurring-task-service"
        dapr.io/app-port: "8000"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - name: recurring-task-service
        image: "{{ .Values.recurringTaskService.image.repository }}:{{ .Values.recurringTaskService.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.recurringTaskService.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: 8000
        livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
        readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: neon-db-secret
              key: connection-string
        - name: ENABLE_DAPR
          value: "true"
        - name: DAPR_PUBSUB_NAME
          value: "kafka-pubsub"